# Generated by Django 2.0b1 on 2017-11-01 11:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('prenume', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Actori',
            },
        ),
        migrations.CreateModel(
            name='Distributie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('actors', models.ManyToManyField(to='main_app.Actor')),
            ],
            options={
                'verbose_name_plural': 'Distributie',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=150)),
                ('descriere', models.TextField(default=' ')),
                ('data_lansare', models.DateField(null=True)),
                ('link_Youtube', models.URLField()),
                ('link_IMDB', models.URLField()),
                ('rating', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Filme',
            },
        ),
        migrations.CreateModel(
            name='Gen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Genuri',
            },
        ),
        migrations.CreateModel(
            name='GenuriFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Film')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Gen')),
            ],
            options={
                'verbose_name_plural': 'Gen Film',
            },
        ),
        migrations.CreateModel(
            name='Regie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Film')),
            ],
            options={
                'verbose_name_plural': 'Regie',
            },
        ),
        migrations.CreateModel(
            name='Regizor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('prenume', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Regizori',
            },
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_nasterii', models.DateTimeField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Barbat'), ('F', 'Femeie')], max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='distributie',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Film'),
        ),
    ]
